#ifndef _a20216dcf746d404e9896fbeb2d26934
#define _a20216dcf746d404e9896fbeb2d26934

#include <string>
#include <list>
#include <cstdint>
#include <functional>
#include <mdns/address.hpp>

namespace mdns {

class IfIndex
{
public:
    using Type = int;

    constexpr IfIndex(Type index) : m_value(index) {}
    constexpr Type value() const noexcept { return m_value; }
    static constexpr IfIndex any() noexcept { return IfIndex(-1); }
    constexpr auto operator<=>(const IfIndex&) const noexcept = default;
private:
    int m_value;
    friend std::ostream& operator<<(std::ostream& o, const IfIndex& i);
};

enum class Protocol
{
    ipv4,
    ipv6,
    unspec, // unspecified
};
std::ostream& operator<<(std::ostream&, const Protocol&);


enum class LookupFlags : int
{
    none          = 0,
    use_wide_area = 1<<0,
    use_multicast = 1<<1,
    no_txt        = 1<<2,
    no_address    = 1<<3,
};
LookupFlags operator|(LookupFlags lhs, LookupFlags rhs);
LookupFlags operator&(LookupFlags lhs, LookupFlags rhs);
LookupFlags operator^(LookupFlags lhs, LookupFlags rhs);
LookupFlags operator~(LookupFlags f);
LookupFlags& operator|=(LookupFlags& lhs, LookupFlags rhs);
LookupFlags& operator&=(LookupFlags& lhs, LookupFlags rhs);
LookupFlags& operator^=(LookupFlags& lhs, LookupFlags rhs);
std::ostream& operator<<(std::ostream& os, LookupFlags f);

enum class ResultFlags : int
{
    none      = 0,
    cached    = 1<<0,
    wide_area = 1<<1,
    multicast = 1<<2,
    local     = 1<<3,
    our_own   = 1<<4,
    static_   = 1<<5,
};
ResultFlags operator|(ResultFlags lhs, ResultFlags rhs);
ResultFlags operator&(ResultFlags lhs, ResultFlags rhs);
ResultFlags operator^(ResultFlags lhs, ResultFlags rhs);
ResultFlags operator~(ResultFlags f);
ResultFlags& operator|=(ResultFlags& lhs, ResultFlags rhs);
ResultFlags& operator&=(ResultFlags& lhs, ResultFlags rhs);
ResultFlags& operator^=(ResultFlags& lhs, ResultFlags rhs);
std::ostream& operator<<(std::ostream& os, ResultFlags f);

enum class ClientFlags : int
{
    none               = 0,
    ignore_user_config = 1<<0,
    no_fail            = 2<<0,
};
ClientFlags operator|(ClientFlags lhs, ClientFlags rhs);
ClientFlags operator&(ClientFlags lhs, ClientFlags rhs);
ClientFlags operator^(ClientFlags lhs, ClientFlags rhs);
ClientFlags operator~(ClientFlags f);
ClientFlags& operator|=(ClientFlags& lhs, ClientFlags rhs);
ClientFlags& operator&=(ClientFlags& lhs, ClientFlags rhs);
ClientFlags& operator^=(ClientFlags& lhs, ClientFlags rhs);
std::ostream& operator<<(std::ostream& os, ClientFlags f);

enum class PublishFlags : int
{
    none           = 0,
    unique         = 1<<0,
    no_probe       = 1<<1,
    no_announce    = 1<<2,
    allow_multiple = 1<<3,
    no_reverse     = 1<<4,
    no_cookie      = 1<<5,
    update         = 1<<6,
    use_wide_area  = 1<<7,
    use_multicast  = 1<<8,
};
PublishFlags operator|(PublishFlags lhs, PublishFlags rhs);
PublishFlags operator&(PublishFlags lhs, PublishFlags rhs);
PublishFlags operator^(PublishFlags lhs, PublishFlags rhs);
PublishFlags operator~(PublishFlags f);
PublishFlags& operator|=(PublishFlags& lhs, PublishFlags rhs);
PublishFlags& operator&=(PublishFlags& lhs, PublishFlags rhs);
PublishFlags& operator^=(PublishFlags& lhs, PublishFlags rhs);
std::ostream& operator<<(std::ostream& os, PublishFlags f);

enum class ClientState
{
    registering,
    running,
    collision,
    failure,
    connecting,
};
std::ostream& operator<<(std::ostream&, const ClientState&);

enum class BrowserEvent
{
    new_,
    remove,
    cache_exhausted,
    all_for_now,
    failure,
};
std::ostream& operator<<(std::ostream&, const BrowserEvent&);

enum class ResolverEvent
{
    found,
    failure,
};
std::ostream& operator<<(std::ostream&, const ResolverEvent&);

enum class DomainBrowserType
{
    browse,
    browse_default,
    register_,
    register_default,
    browse_legacy,
};
std::ostream& operator<<(std::ostream&, const DomainBrowserType&);

enum class DnsType : uint16_t
{
    a     = 0x01, // RFC 1035
    ns    = 0x02, // RFC 1035
    cname = 0x05, // RFC 1035
    soa   = 0x06, // RFC 1035
    ptr   = 0x0C, // RFC 1035
    hinfo = 0x0D, // RFC 8482
    mx    = 0x0F, // RFC 1035
    txt   = 0x10, // RFC 1035
    aaaa  = 0x1C, // RFC 3596
    srv   = 0x21, // RFC 2782
};
std::ostream& operator<<(std::ostream&, const DnsType&);

enum class GroupState{
    uncommitted,
    registering,
    established,
    collision,
    failure
};
std::ostream& operator<<(std::ostream&, const GroupState&);

typedef std::list<std::string> StrList;

struct DeviceInfo
{
    IfIndex interface = IfIndex::any();
    Protocol protocol = Protocol::unspec;
};

// Generated by DomainBrowser
// Input to DomainBrowser, ServiceTypeBrowser, HostNameResolver, AddressResolver
struct DomainInfo : public DeviceInfo
{
    std::string domain = "local";
};

// Generated by ServiceTypeBrowser
// Input to ServiceBrowser
struct TypeInfo : public DomainInfo
{
    std::string type;
};

// Generated by ServiceBrowser
// Input to ServiceResolver
struct ServiceInfo : public TypeInfo
{
    std::string name;
};

struct ServiceDetails : ServiceInfo
{
    std::string hostname;
    uint16_t port;
    StrList txt;
};

// Needed to publish a service
struct ServiceRecord : ServiceDetails
{
    StrList subtypes;
};

// Generated by ServiceResolver
struct ResolvedServiceInfo : public ServiceDetails
{
    Address addr;
};

// Generated by AddressResolver, HostNameResolver
// Input to Group::AddHost() to publish a Hostname/Address pair
struct AddressHostnameInfo : public DeviceInfo
{
    std::string hostname;
    Address addr;
};

// Input to RecordBrowser
struct RecordRequest : public DeviceInfo
{
    std::string name; // Name of record (hostname?)
    DnsType type; // Type of record A,AAAA,CNAME,PTR,TXT,MX,NS,SOA,HINFO,SRV
};

// Generated by RecordBrowser
struct RecordResult : public RecordRequest
{
    // Ex: case AVAHI_DNS_TYPE_A:    4-byte in_addr
    //     case AVAHI_DNS_TYPE_AAAA: 16-byte in_addr
    //     case AVAHI_DNS_TYPE_PTR:  can be decoded with avahi_dns_packet_consume_name()
    const void *rdata; // raw DNS data.  Size/contents changes based on type
    size_t size; // size of rdata
};

// Input to Group::AddRecord().  Publish a low-level record
struct DnsRecord : public RecordResult
{
    uint32_t ttl;
};

typedef std::function<void(
    ClientState
)> ClientCallback;

typedef std::function<void(
    BrowserEvent,
    TypeInfo,
    ResultFlags,
    std::error_code
)> ServiceTypeCallback;

typedef std::function<void(
    BrowserEvent,
    ServiceInfo,
    ResultFlags,
    std::error_code
)> ServiceCallback;

typedef std::function<void(
    BrowserEvent,
    DomainInfo,
    ResultFlags,
    std::error_code
)> DomainCallback;

typedef std::function<void(
    BrowserEvent,
    RecordResult,
    ResultFlags,
    std::error_code
)> RecordCallback;

typedef std::function<void(
    ResolverEvent,
    AddressHostnameInfo,
    ResultFlags,
    std::error_code
)> AddressCallback;

typedef std::function<void(
    ResolverEvent,
    ResolvedServiceInfo,
    ResultFlags,
    std::error_code
)> ResolvedServiceCallback;

typedef std::function<void(
    std::string, // Group name
    GroupState,
    std::error_code
)> GroupCallback;

}
#endif
